#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ClassLibrary1.Resource", IsApplication=false)]

namespace ClassLibrary1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public static int codes = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int hint_color = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int hint_text = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int text_color = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int underline_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int underline_selected_color = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f020002
			public static int hintColor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int textColor = 2130837507;
			
			// aapt resource value: 0x7f020000
			public static int underline_default_color = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int underline_selected_color = 2130837505;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030007
			public static int hint_margin_bottom = 2130903047;
			
			// aapt resource value: 0x7f030004
			public static int hint_size = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int hint_small_size = 2130903045;
			
			// aapt resource value: 0x7f030002
			public static int section_reduction = 2130903042;
			
			// aapt resource value: 0x7f030006
			public static int text_margin_bottom = 2130903046;
			
			// aapt resource value: 0x7f030003
			public static int text_size = 2130903043;
			
			// aapt resource value: 0x7f030000
			public static int underline_stroke_width = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int underline_width = 2130903041;
			
			// aapt resource value: 0x7f030008
			public static int view_height = 2130903048;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] core_area = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 5
			public static int core_area_codes = 5;
			
			// aapt resource value: 2
			public static int core_area_hint_color = 2;
			
			// aapt resource value: 4
			public static int core_area_hint_text = 4;
			
			// aapt resource value: 3
			public static int core_area_text_color = 3;
			
			// aapt resource value: 0
			public static int core_area_underline_color = 0;
			
			// aapt resource value: 1
			public static int core_area_underline_selected_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
